Class {
	#name : #MmVariableMappedAnnouncement,
	#superclass : #Announcement,
	#instVars : [
		'mappedTo'
	],
	#category : #'Metamath-Bloc'
}

{ #category : #'as yet unclassified' }
MmVariableMappedAnnouncement >> mappedTo [

^ mappedTo
]

{ #category : #'as yet unclassified' }
MmVariableMappedAnnouncement >> mappedTo: s [

mappedTo := s
]

{ #category : #'as yet unclassified' }
MmVariableMappedAnnouncement >> stuff: s [
]
